services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=project_management
      - POSTGRES_PASSWORD=qqq
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - "./postgres_data:/var/lib/postgresql/data/"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'project-management-app'
    ports:
      - 8080:8080
    depends_on:
      - postgres